spring:
  application:
    name: ribbon-consumer
server:
  port: 9001
eureka:
  client:
    serviceUrl.defaultZone: http://localhost:1111/eureka/
    registry-fetch-interval-seconds: 10
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 15000

ribbon:
  ReadTimeout: 20000
#请求连接的超时时间
  ConnectTimeout: 20000